### ISSUE TITLE
Pawn and bishop icons are the wrong way

### ISSUE THREAD

**Issue by klemmari1** [Piterden/chessbot#23]
As the title says, bishop and pawn icons should be the other way around.

**Comment by pubmania** [comment]
That's true... the problem is in the file `chessbot/src/helpers/index.js`

![Screenshot_20200503-092256_Gallery](https://user-images.githubusercontent.com/1966557/80909470-9ebedd80-8d20-11ea-9c61-002800ee533d.jpg)

**Comment by Piterden** [comment]
It has been fixed
