### ISSUE TITLE
TypeError: leaveHandler is not a function

### ISSUE THREAD

**Issue by lattice0** [Piterden/chessbot#25]
I started dockerizing and made these modifications:

https://github.com/Piterden/chessbot/compare/master...lucaszanella:master

Now I'm getting

```
web_1    | [nodemon] starting `node src/index.js`
web_1    | /home/node/app/src/scenes/game/index.js:11
web_1    |   .leave(...leaveHandler())
web_1    |             ^
web_1    | 
web_1    | TypeError: leaveHandler is not a function

```

Is the code complete? Can't find all the handlers in

```
module.exports = new Scene('game')
  .leave(...leaveHandler())
  .enter(...startHandler())
  .action(...movesHandler())
  .action(...actionsHandler())
```

on the code

**Comment by lattice0** [comment]
I also had to change `const { gameScene } = require('@/scenes/')` to `const { gameScene } = require('@/scenes/game')` as you see in the diff, so it looks like the code is not complete

**Comment by Piterden** [comment]
Hi, my friend.

`dev` branch is online for now. `master` has old code

**Comment by Piterden** [comment]
I think it is solved for now
